Main app
erezfree29/Metrics-webapp pull request #2
Opened 2021-09-22 04:53 UTC by erezfree29

This is a final capstone project app.
The app fetches information from the https://www.scorebat.com API.
It displays recent matches of Europe's top leagues, clicking on an image will link the user to a video of the match.

2021-09-22 05:52 UTC, mricanho requested changes
Hi @erezfree29, 

You are following the gitflow, your README file is complete, your commit messages are good and your video presentation was ok, you are already receiving information from the API, a good start! 🔥🔥

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] You have work to do, first read again the requirements for this capstone, this must be a single page application (SPA), it must have a home page and a details page, as well as a category filter in the home page, right now you only have a Home Page and when you click an element it points out of the application to www.scorebat.com, this is not the assignment, please add a details page with numeric information about the matches.

- [ ] You are not following the layout or the design, you need to copy the exact layout and choose a pallet color (whatever you like) that mimics the original design, this is a hard requirement.

![imagen](https://user-images.githubusercontent.com/60631456/134289897-fd57d614-e782-4034-adb7-3b035428dfdd.png)

Original design home page and details page:

![imagen](https://user-images.githubusercontent.com/60631456/134289987-2accb145-88c0-41a8-8dfc-cf2643d0bd54.png)

Your design:

![imagen](https://user-images.githubusercontent.com/60631456/134290193-9de4c87c-f194-4c87-a8fd-d3e73dfc90f3.png)

- [ ] Add more unit tests for pure functions in your Redux code.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-22 05:52 UTC, mricanho commented on src/components/dr
> +</>
- [ ] This file doesn't belong to this project, please remove it

2021-09-22 05:52 UTC, mricanho commented on src/components/dra
> +  </nav>
- [ ] This file doesn't belong to this project, please remove it

2021-09-23 09:15 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-10-06 08:38 UTC, merged